server_name = "matrix.palpo.im"
listen_addr = "0.0.0.0:8008"

# Enables registration. If set to false, no users can register on this server.
allow_registration = true

# Servers listed here will be used to gather public keys of other servers.
# Generally, copying this exactly should be enough. (Currently, Palpo doesn't
# support batched key requests, so this list should only contain Synapse
# servers.)
trusted_servers = ["matrix.org"]

[db]
url = "postgres://palpo:changeme@postgres:5432/palpo"
pool_size = 10

[well_known]
# Palpo handles the /.well-known/matrix/* endpoints, making both clients and servers try to access palpo with the host
# server_name and port 443 by default.
# If you want to override these defaults, uncomment and edit the following lines accordingly:
server = "matrix.palpo.im"
client = "https://matrix.palpo.im"