services:
    caddy:
    # 此 compose 文件使用 caddy-docker-proxy 作为 palpo 的反向代理！
    # 更多信息，请访问 https://github.com/lucaslorentz/caddy-docker-proxy
        image: lucaslorentz/caddy-docker-proxy:ci-alpine
        ports:
            - 80:80
            - 443:443
        environment:
            - CADDY_INGRESS_NETWORKS=caddy
        networks:
            - caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data:/data
        restart: unless-stopped
        labels:
            caddy: example.com
            caddy.0_respond: /.well-known/matrix/server {"m.server":"matrix.example.com:443"}
            caddy.1_respond: /.well-known/matrix/client {"m.server":{"base_url":"https://matrix.example.com"},"m.homeserver":{"base_url":"https://matrix.example.com"},"org.matrix.msc3575.proxy":{"url":"https://matrix.example.com"}}

    homeserver:
        ### 如果您已经使用 'docker build' 构建了 palpo 镜像，或者想使用注册表镜像，
        ### 那么您就可以开始了。
        image: chrislearn/palpo:latest
        restart: unless-stopped
        volumes:
            - db:/var/lib/palpo
            #- ./palpo.toml:/etc/palpo.toml
        environment:
            PALPO_CONFIG: '/var/palpo/palpo.toml'
        networks:
            - caddy
        labels:
            caddy: matrix.example.com
            caddy.reverse_proxy: "{{upstreams 6167}}"

volumes:
    db:

networks:
    caddy:
        external: true