# palpo - Traefik 反向代理之后

services:
  homeserver:
    ### 如果您已经使用 'docker build' 构建了 palpo 镜像，或者想使用 Docker Hub 镜像，
    ### 那么您就可以开始了。
    image: privoce/vocechat-matrix-palpo:main
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PALPO_CONFIG: '/var/palpo/palpo.toml'
    volumes:
      - $PWD/palpo.toml:/var/palpo/palpo.toml
      - $PWD/data/media:/var/palpo/media
    ulimits: # palpo 使用相当多的文件描述符，在某些系统上默认为 1024，因此您可以告诉 docker 增加它
      nofile:
        soft: 1048567
        hard: 1048567
volumes:
  db:

networks:
  # 这是 Traefik 监听的网络，如果您的网络有不同的名称，
  # 不要忘记在此处和 compose.override.yml 中更改它
  proxy:
    external: true