services:
    caddy:
    # 此 compose 文件使用 caddy-docker-proxy 作为 palpo 的反向代理！
    # 更多信息，请访问 https://github.com/lucaslorentz/caddy-docker-proxy
        image: lucaslorentz/caddy-docker-proxy:ci-alpine
        ports:
            - 80:80
            - 443:443
        environment:
            - CADDY_INGRESS_NETWORKS=caddy
        networks:
            - caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data:/data
        restart: unless-stopped
        labels:
            caddy: example.com
            caddy.0_respond: /.well-known/matrix/server {"m.server":"matrix.example.com:443"}
            caddy.1_respond: /.well-known/matrix/client {"m.server":{"base_url":"https://matrix.example.com"},"m.homeserver":{"base_url":"https://matrix.example.com"},"org.matrix.msc3575.proxy":{"url":"https://matrix.example.com"}}

    homeserver:
        ### 如果您已经使用 'docker build' 构建了 palpo 镜像，或者想使用注册表镜像，
        ### 那么您就可以开始了。
        image: chrislearn/palpo:latest
        restart: unless-stopped
        volumes:
            - db:/var/lib/palpo
            #- ./palpo.toml:/etc/palpo.toml
        environment:
            PALPO_SERVER_NAME: example.com # 编辑此处
            PALPO_DATABASE_PATH: /var/lib/palpo
            PALPO_PORT: 6167
            PALPO_MAX_REQUEST_SIZE: 20000000 # 字节，约 20 MB
            PALPO_ALLOW_REGISTRATION: 'true'
            PALPO_REGISTRATION_TOKEN: 'YOUR_TOKEN' # 允许注册时需要注册令牌。
            #PALPO_YES_I_AM_VERY_VERY_SURE_I_WANT_AN_OPEN_REGISTRATION_SERVER_PRONE_TO_ABUSE: 'true'
            PALPO_ALLOW_FEDERATION: 'true'
            PALPO_ALLOW_CHECK_FOR_UPDATES: 'true'
            PALPO_TRUSTED_SERVERS: '["matrix.org"]'
            #PALPO_LOG: warn,state_res=warn
            PALPO_ADDRESS: 0.0.0.0
            #PALPO_CONFIG: '/etc/palpo.toml' # 如果您在上面映射了 config toml，请取消注释
        networks:
            - caddy
        labels:
            caddy: matrix.example.com
            caddy.reverse_proxy: "{{upstreams 6167}}"

volumes:
    db:

networks:
    caddy:
        external: true