# palpo

services:
    homeserver:
        ### If you already built the palpo image with 'docker build' or want to use a registry image,
        ### then you are ready to go.
        image: chrislearn/palpo:latest
        restart: unless-stopped
        ports:
            - 8448:6167
        volumes:
            - db:/var/lib/palpo
            #- ./palpo.toml:/etc/palpo.toml
        environment:
            PALPO_SERVER_NAME: your.server.name # EDIT THIS
            PALPO_DATABASE_PATH: /var/lib/palpo
            PALPO_PORT: 6167
            PALPO_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
            PALPO_ALLOW_REGISTRATION: 'true'
            PALPO_REGISTRATION_TOKEN: 'YOUR_TOKEN' # A registration token is required when registration is allowed.
            #PALPO_YES_I_AM_VERY_VERY_SURE_I_WANT_AN_OPEN_REGISTRATION_SERVER_PRONE_TO_ABUSE: 'true'
            PALPO_ALLOW_FEDERATION: 'true'
            PALPO_ALLOW_CHECK_FOR_UPDATES: 'true'
            PALPO_TRUSTED_SERVERS: '["matrix.org"]'
            #PALPO_LOG: warn,state_res=warn
            PALPO_ADDRESS: 0.0.0.0
            #PALPO_CONFIG: '/etc/palpo.toml' # Uncomment if you mapped config toml above
    #
    ### Uncomment if you want to use your own Element-Web App.
    ### Note: You need to provide a config.json for Element and you also need a second
    ###       Domain or Subdomain for the communication between Element and palpo
    ### Config-Docs: https://github.com/vector-im/element-web/blob/develop/docs/config.md
    # element-web:
    #     image: vectorim/element-web:latest
    #     restart: unless-stopped
    #     ports:
    #         - 8009:80
    #     volumes:
    #         - ./element_config.json:/app/config.json
    #     depends_on:
    #         - homeserver

volumes:
    db:
