# palpo - Traefik 反向代理之后

services:
  homeserver:
    ### 如果您已经使用 'docker build' 构建了 palpo 镜像，或者想使用 Docker Hub 镜像，
    ### 那么您就可以开始了。
    image: privoce/vocechat-matrix-palpo:main
    restart: unless-stopped
    volumes:
      - db:/var/lib/palpo
      #- ./palpo.toml:/etc/palpo.toml
    networks:
      - proxy
    environment:
      PALPO_SERVER_NAME: your.server.name.example # 编辑此处
      PALPO_DATABASE_PATH: /var/lib/palpo
      PALPO_PORT: 6167 # 应该与负载均衡器 Traefik 标签匹配
      PALPO_MAX_REQUEST_SIZE: 20000000 # 字节，约 20 MB
      PALPO_ALLOW_REGISTRATION: 'true'
      PALPO_REGISTRATION_TOKEN: 'YOUR_TOKEN' # 允许注册时需要注册令牌。
      #PALPO_YES_I_AM_VERY_VERY_SURE_I_WANT_AN_OPEN_REGISTRATION_SERVER_PRONE_TO_ABUSE: 'true'
      PALPO_ALLOW_FEDERATION: 'true'
      PALPO_ALLOW_CHECK_FOR_UPDATES: 'true'
      PALPO_TRUSTED_SERVERS: '["matrix.org"]'
      #PALPO_LOG: warn,state_res=warn
      PALPO_ADDRESS: 0.0.0.0
      #PALPO_CONFIG: '/etc/palpo.toml' # 如果您在上面映射了 config toml，请取消注释

      # 我们需要某种方式来提供客户端和服务器的 .well-known json。最简单的方法是通过 PALPO_WELL_KNOWN
      # 变量/配置选项，有多种方法可以做到这一点，例如在 palpo.toml 文件中，以及在单独的
      # 有关委托的更多信息，请参阅覆盖文件
      PALPO_WELL_KNOWN: |
        {
        client=https://your.server.name.example,
        server=your.server.name.example:443
        }
    #cpuset: "0-4" # 取消注释以限制到特定的 CPU 内核
    ulimits: # palpo 使用相当多的文件描述符，在某些系统上默认为 1024，因此您可以告诉 docker 增加它
      nofile:
        soft: 1048567
        hard: 1048567

    ### 如果您想使用自己的 Element-Web App，请取消注释。
    ### 注意：您需要为 Element 提供一个 config.json，并且您还需要第二个
    ###       用于 Element 和 palpo 之间通信的域名或子域名
    ### 配置文档：https://github.com/vector-im/element-web/blob/develop/docs/config.md
    # element-web:
    #     image: vectorim/element-web:latest
    #     restart: unless-stopped
    #     volumes:
    #         - ./element_config.json:/app/config.json
    #     networks:
    #         - proxy
    #     depends_on:
    #         - homeserver

volumes:
  db:

networks:
  # 这是 Traefik 监听的网络，如果您的网络有不同的名称，
  # 不要忘记在此处和 docker-compose.override.yml 中更改它
  proxy:
    external: true

# vim: ts=2:sw=2:expandtab