# palpo

services:
    homeserver:
        ### 如果您已经使用 'docker build' 构建了 palpo 镜像，或者想使用注册表镜像，
        ### 那么您就可以开始了。
        image: jevolk/palpo:latest
        restart: unless-stopped
        ports:
            - 8448:6167
        volumes:
            - db:/var/lib/palpo
            #- ./palpo.toml:/etc/palpo.toml
        environment:
            PALPO_SERVER_NAME: your.server.name # 编辑此处
            PALPO_DATABASE_PATH: /var/lib/palpo
            PALPO_PORT: 6167
            PALPO_MAX_REQUEST_SIZE: 20000000 # 字节，约 20 MB
            PALPO_ALLOW_REGISTRATION: 'true'
            PALPO_REGISTRATION_TOKEN: 'YOUR_TOKEN' # 允许注册时需要注册令牌。
            #PALPO_YES_I_AM_VERY_VERY_SURE_I_WANT_AN_OPEN_REGISTRATION_SERVER_PRONE_TO_ABUSE: 'true'
            PALPO_ALLOW_FEDERATION: 'true'
            PALPO_ALLOW_CHECK_FOR_UPDATES: 'true'
            PALPO_TRUSTED_SERVERS: '["matrix.org"]'
            #PALPO_LOG: warn,state_res=warn
            PALPO_ADDRESS: 0.0.0.0
            #PALPO_CONFIG: '/etc/palpo.toml' # 如果您在上面映射了 config toml，请取消注释
    #
    ### 如果您想使用自己的 Element-Web App，请取消注释。
    ### 注意：您需要为 Element 提供一个 config.json，并且您还需要第二个
    ###       用于 Element 和 palpo 之间通信的域名或子域名
    ### 配置文档：https://github.com/vector-im/element-web/blob/develop/docs/config.md
    # element-web:
    #     image: vectorim/element-web:latest
    #     restart: unless-stopped
    #     ports:
    #         - 8009:80
    #     volumes:
    #         - ./element_config.json:/app/config.json
    #     depends_on:
    #         - homeserver

volumes:
    db: